Repository terraware/web-components, pull requests merged in 2024-04, with the labels that each got.

#494 Add package resolution for @babel/traverse @ 7.24.1
  package.json
  yarn.lock
Labels: patch

#495 SW-4795 Apply "font-variant-numeric: tabular-nums" to all table columns
  src/components/table/TableCellRenderer.tsx
Labels: patch

#496 SW-5165 Added fontWeight and fontStyle to list item options
  src/components/Dropdown.tsx
  src/components/types/index.ts
  src/stories/Dropdown.stories.tsx
Labels: patch

#497 Allow cells in table to be right aligned
  src/components/table/TableCellRenderer.tsx
  src/components/table/TableHeader.tsx
  src/components/table/TableHeaderItem.tsx
  src/components/table/index.tsx
  src/components/table/types.ts
  src/stories/Table.stories.tsx
Labels: patch

#500 Align table header label and icons to the right when column is right aligned
  src/components/IconTooltip/index.tsx
  src/components/table/TableHeaderItem.tsx
  src/stories/Table.stories.tsx
Labels: patch

#499 SW-4662 Avoid flash of dropdown menu before it's position is calculated/repositioned
  package.json
  src/components/Select/SelectT.tsx
  src/components/Select/styles.scss
  src/stories/Select.stories.tsx
Labels: patch

#504 SW-4662 More fixedMenu fixes, handle scroll
  package.json
  src/components/Select/SelectT.tsx
  src/stories/Select.stories.tsx
Labels: patch

#507 SW-4662 Don't resize dropdown during scroll
  src/components/Select/SelectT.tsx
Labels: patch

#508 Add ability to optionally add icon to a tab
  package.json
  src/components/Tabs/index.tsx
  src/stories/Tabs.stories.tsx
Labels: minor

#510 SW-5122 Add ability to style the Select component
  package.json
  src/components/Dropdown.tsx
  src/components/Icon/Icon.tsx
  src/components/Select/Select.tsx
  src/components/Select/SelectT.tsx
  src/stories/Select.stories.tsx
Labels: minor

#505 SW-2719 Refactor DatePicker and utils to use luxon
  docs/license-report.html
  package.json
  src/components/DatePicker/DatePicker.tsx
  src/index.ts
  src/stories/DatePicker.stories.tsx
  src/utils/date.test.ts
  src/utils/date.ts
  src/utils/date.v1.ts
  src/utils/index.ts
  yarn.lock
Labels: minor

#511 SW-4597 Use TW brand color for busy spinner
  src/components/BusySpinner/index.tsx
Labels: patch

#512 Revert "Bump @mui/material from 5.15.3 to 5.15.15 (#502)"
  package.json
  yarn.lock
Labels: patch

#513 Update to: - @mui/material: ^5.15.15 - @mui/styles: ^5.15.15"
  package.json
  src/components/Autocomplete/Autocomplete.tsx
  src/stories/Autocomplete.stories.tsx
  yarn.lock
Labels: patch

#515 Update emotion styled to match emotion react
  package.json
  yarn.lock
Labels: patch

#514 SW-5218 Fix datepicker adapter for luxon
  package.json
  src/components/DatePicker/DatePicker.tsx
Labels: patch

#516 Fix package.json
  package.json
Labels: patch

#517 Fix package.json version again to trigger npm publish
  package.json
Labels: patch

#528 Trigger correct major version update
  package.json
Labels: UPDATE-MAJOR

#529 Change package.json version to trigger npm publish
  package.json
Labels: major

#530 SW-4653 Bump babel-loader version for node 18 compatibility in vercel
  package.json
  yarn.lock
Labels: patch
